spring:
  application:
    name:
      QuoraApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_db
      username: root
      password: root
      auto-index-creation: true
      authentication-database: admin

server:
  port: 8001
